### ISSUE TITLE
Forwarding should be double-checked

### ISSUE THREAD

**Issue by Krzmbrzl** [ValeevGroup/SeQuant#108]
This is touching on the same topic as #99 but while browsing through the code some more, I found another instance that can potentially invoke undefined behavior:
https://github.com/ValeevGroup/SeQuant/blob/482df252dc4fbc670d7f98aab8f41862e86ed49d/SeQuant/domain/eval/eval.hpp#L703-L707
if `cm` is an rvalue reference, then the first call to `std::forward` will `move` from it, leaving `cm` in an undefined state. Thus, the subsequent access to `cm` is likely to yield odd results.

In general, the way perfect forwarding is used here, doesn't make sense. Perfect forwarding (and thus taking parameters by universal/forwarding reference) only makes sense, if at some point you'll need a copy of that value _or_ you call another function that takes a universal reference (and thus somewhere down the call chain, a copy will be needed) (or you want to make the function return the parameter as the same type as you took it in).
If you don't need to copy the provided parameter, it makes more sense to simply take it in as a (const) reference.

This should eliminate a couple of uses of universal references and thus the possibility to `forward` them. For the remaining parts, one has to ask oneself: is the code still valid, if I write `std::move` here (assuming I got an rvalue reference in) or does this lead to a use-after-move scenario? And only in those places, where moving wouldn't cause issues, can `std::forward` be safely used.
(Those cases where moving doesn't make sense should already been removed by the "check if we need a copy" rule)

**Comment by bimalgaudel** [comment]
Addressed in PR #117

**Comment by bimalgaudel** [comment]
Completed in PR #117
