### ISSUE TITLE
Single-term optimization SegFaults for full contractions

### ISSUE THREAD

**Issue by Krzmbrzl** [ValeevGroup/SeQuant#114]
## The problem

If `single_term_opt` is tasked with optimizing a full contraction between three or more tensors, it can/will SegFault.

The concrete example for which I observe the single-term optimization producing a segmentation fault is
$t^{o_1 o_2}_{v_1 v_2} f^{v_1}_{v_3} \Gamma^{v_2 v_3}_{o_1 o_2}$.
This is part of a stationary energy functional ("Lagrangian") expression (thus the appearance of the unusual full contractions of three tensors).

The last iteration (for finding the optimal contraction order  of the binary contraction with the remaining tensor) will find three equivalent possibilities (that are not considered as equivalent due to floating point numerics, but that doesn't matter here), but in each of these cases `diffs` will be empty as this is a full contraction:
https://github.com/ValeevGroup/SeQuant/blob/c338d25fb11c885e6d1cfeef3bb92640435a6df4/SeQuant/core/optimize.hpp#L172-L190

Thus, `curr_indices` will be empty, causing us to enter
https://github.com/ValeevGroup/SeQuant/blob/c338d25fb11c885e6d1cfeef3bb92640435a6df4/SeQuant/core/optimize.hpp#L195-L200
which - as the comment indicates - expects to only be entered for "non-contractions" (aka: just evaluating a single tensor on its own). In the described case however, `power_pos = 3` as  we have already entered this branch for the three individual tensors in our expression. This will then cause
https://github.com/ValeevGroup/SeQuant/blob/c338d25fb11c885e6d1cfeef3bb92640435a6df4/SeQuant/core/optimize.hpp#L198
to access out-of-bounds as the size of `nth_tensor_indices` has only three entries.

## Possible fix

I would suggest to use a boolean flag to indicate whether or not we are currently looking at a contraction (in which case `scan_parts` will be called) or an atomic tensor (in which case `scan_parts` will NOT be called) and then branch on that flag rather than on whether or not we have any external indices.

Based on a quick test, this fixes the issue.

If I haven't overlooked something and you approve of this fix, I will create a PR tomorrow.

**Comment by bimalgaudel** [comment]
It has already been addressed in this commit: cfcede405ef419e8273564153b7c4c83932ea27d

**Comment by Krzmbrzl** [comment]
Could we decouple this fix from the feature branch it is currently in such that it an be merged independently (in a timely fashion)?

@bimalgaudel any particular reason that you chose a more complicated approach than a simple boolean flag to check whether there has been a contraction or not?

**Comment by bimalgaudel** [comment]
@Krzmbrzl I do not have any other particular reason other than how I saw it could be done. Could you elaborate on how and where to create and update such a boolean flag? Inside the `scan_parts` lambda?

**Comment by bimalgaudel** [comment]
Pull request for this issue: #116

**Comment by Krzmbrzl** [comment]
> Could you elaborate on how and where to create and update such a boolean flag? Inside the scan_parts lambda?

Yes. Define a boolean variable outside of the lamda and initialize it to `false`, capture the flag in the lambda (by reference) and set it to `true`  if the lambda is invoked.
Since the lambda will only be invoked if the given binary representation of `n` can be partitioned into two numbers that are bother != zero, the flag will only be set to `true` if there is more than one bit set in `n`, which corresponds to a contraction having been performed.
