### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by Krzmbrzl** [ValeevGroup/SeQuant#115]
I would ask y'all a couple of questions that I - so far - have not yet found answers to. Thus, I am hoping that someone of you can help me out here:
- What are proto indices and what/where are they used?
- What is the meaning of the `MultiProductVacuum`?
- It seems that one has to specify all tensors that are used as a list of "cardinal" tensors, which determines the order of the tensors in the canonical form. Is there something more to the meaning of cardinal tensors and the order in which they are defined? And if the order in the canonical form is all that these are used for, why aren't tensors not explicitly listed in that list simply sorted based on e.g. alphabetic order?

**Comment by evaleev** [comment]
> * What are proto indices and what/where are they used?

These are for PNO-like methods. E.g. `a^{i,j}` denotes that the basis for space denoted by `a` (i.e. `active_unoccupied`) depends on the values of "proto" indices `i` and `j` ( (i.e. `active_occupied`). It's possible to derive and even evaluate some types of expressions involving indices with protoindices, but the support is incomplete hence these are not documented.

> * What is the meaning of the `MultiProductVacuum`?

vacuum represented by a linear combination of determinants (products). Currently `WickTheorem` does not implement support for such vacuum directly (it's possible to use physical or fermi vacuum as a workaround) but may do so in the future.

> * It seems that one has to specify all tensors that are used as a list of "cardinal" tensors, which determines the order of the tensors in the canonical form. Is there something more to the meaning of cardinal tensors and the order in which they are defined? And if the order in the canonical form is all that these are used for, why aren't tensors not explicitly listed in that list simply sorted based on e.g. alphabetic order?

People are peculiar and wants things in particular order, so `cardinal_tensor_labels` exists for producing equations that look "conventional" to humans. E.g. tensors of operators (i.e., normal operator, with label `a`) should appear after tensors of scalars (e.g. even those labeled `z`). define the order in which tensors should appear.

**Comment by Krzmbrzl** [comment]
Thank you for your answers! :+1: 

> People are peculiar and wants things in particular order, so cardinal_tensor_labels exists for producing equations that look "conventional" to humans. E.g. tensors of operators (i.e., normal operator, with label a) should appear after tensors of scalars (e.g. even those labeled z). define the order in which tensors should appear.

Okay then this really is only for determining the order of tensors in the expression. In that case I'll create a PR that prevents things from crashing if one has forgotten to specify one of the tensors in that list.
