### ISSUE TITLE
unity build broken

### ISSUE THREAD

**Issue by evaleev** [ValeevGroup/SeQuant#155]
and not CI-tested to boot!

<img width="1411" alt="image" src="https://github.com/ValeevGroup/SeQuant/assets/2192487/1b9d44c5-25f7-4cf8-8c20-02a0f1e10c4c">

**Comment by Krzmbrzl** [comment]
Likely related to #142

**Comment by evaleev** [comment]
> Potentially related to #142

I tried #142 but it also fails to unity-build ...

**Comment by Krzmbrzl** [comment]
I was more referring to a more general picture that issues with non-self-contained headers can cause issues in unity builds. Not that this was the reason for this specific failure. Should have formulated that better, sorry.
