### ISSUE TITLE
Bug in tensor hash test case

### ISSUE THREAD

**Issue by Krzmbrzl** [ValeevGroup/SeQuant#179]
https://github.com/ValeevGroup/SeQuant/blob/42558e9f7ca66f76145427d4c8a1bf06715c3029/tests/unit/test_tensor.cpp#L100
This only checks that the comparison doesn't throw and disregards the result of the comparison. I assume this is not the desired behavior? :eyes:

**Comment by evaleev** [comment]
Oh, definitely ... good catch ...
