### ISSUE TITLE
Support for AO spaces

### ISSUE THREAD

**Issue by evaleev** [ValeevGroup/SeQuant#20]
- AO space should have same bitset as the corresponding orthogonal space ... so the difference between the two should be an attribute (AO-specific) bit?

**Comment by Krzmbrzl** [comment]
@evaleev is this resolved by the introduction of runtime index spaces? Based on the issue description, I would think it has been addressed

**Comment by evaleev** [comment]
@Krzmbrzl not sure what I had in mind, honestly :) I think it's fine to close this
