### ISSUE TITLE
New bug in open-shell CCSDTQ

### ISSUE THREAD

**Issue by nakulteke** [ValeevGroup/SeQuant#73]
Some terms have `nan` as constant in open-shell spin-traced CCSDTQ, which is a result of product terms added as expected.
```
& + {{{nan}}{g^{{a⁺_3}{a⁻_3}}_{{a⁺_1}{i⁻_3}}}{t^{{i⁺_1}{i⁻_1}}_{{a⁺_2}{a⁻_3}}}{t^{{i⁺_2}{i⁻_2}{i⁻_3}}_{{a⁺_3}{a⁻_1}{a⁻_2}}}} \\
& + {{{nan}}{g^{{a⁺_3}{a⁻_3}}_{{i⁺_3}{i⁻_3}}}{t^{{i⁺_2}{i⁺_1}{i⁻_1}}_{{a⁺_1}{a⁺_3}{a⁻_3}}}{t^{{i⁺_3}{i⁻_2}{i⁻_3}}_{{a⁺_2}{a⁻_1}{a⁻_2}}}} \\
& + {{{nan}}{g^{{a⁺_3}{a⁻_3}}_{{i⁺_3}{i⁻_3}}}{t^{{i⁺_3}}_{{a⁺_1}}}{t^{{i⁺_1}{i⁻_1}}_{{a⁺_2}{a⁻_3}}}{t^{{i⁺_2}{i⁻_2}{i⁻_3}}_{{a⁺_3}{a⁻_1}{a⁻_2}}}} \\
```

**Comment by evaleev** [comment]
@nakulteke this is likely fixed by the use of rationals instead of floats for representing `Constant` ... ?

**Comment by nakulteke** [comment]
@evaleev No. This was a result of `Constant(sum_of_prefactors / first_prefactor)`  producing a `nan`.  Fixed in commit: https://github.com/ValeevGroup/SeQuant/pull/72/commits/4ef686f16557a403f1c316b32e3b348f22f9db8e
