### ISSUE TITLE
Default convention is incomplete (w.r.t. index space types)

### ISSUE THREAD

**Issue by Krzmbrzl** [ValeevGroup/SeQuant#97]
As far as I can tell, the default QCiFS convention doesn't register all possible index space types.

All types are listed as
https://github.com/ValeevGroup/SeQuant/blob/1dd6257ba9e5b2e9aa2b71eb38768f8a8a1699c7/SeQuant/core/space.hpp#L145-L158
whereas the convention (seems to) only defines
https://github.com/ValeevGroup/SeQuant/blob/1dd6257ba9e5b2e9aa2b71eb38768f8a8a1699c7/SeQuant/domain/mbpt/convention.cpp#L75-L92

Ignoring the null/non-null space types, the following spaces are not covered by the default convention:
- frozen_unoccupied
- inactive_occupied
- inactive_unoccupied

Maybe these spaces are not part of the QCiFS paper series and have therefore left out, but from a user's point of view, it would be very beneficial, if the default convention would indeed register all existing index space types instead of only a subset of them.

**Comment by evaleev** [comment]
@Krzmbrzl As part of #112 I documented these choices as well as extended the convention to include active orbitals (https://github.com/ValeevGroup/SeQuant/pull/112/commits/0177f6592ae9f0304d986126c7b8f7aade63c302) ... as is often the case with historical artifacts the QCiFS "convention" (or, rather, what I define as the convention) is not systematic. I would prefer actually to only keep in the convention the symbols that have been established as part of the convention. I have not seen established uses of all "standard" spaces, so I'd actually rather them undefined.

Note that nothing prevents the user from registering additional choices, e.g.
```
IndexSpace::register_instance(L"m'", IndexSpace::frozen_occupied);

// now can use m'
Index m_1(L"m'");
```
(and defining additional IndexSpaces, etc.). If user wants to add something to the convention they need to make a PR that documents the proposed choice.

**Comment by Krzmbrzl** [comment]
> I would prefer actually to only keep in the convention the symbols that have been established as part of the convention. I have not seen established uses of all "standard" spaces, so I'd actually rather them undefined.

I understand.

The issue only comes about when e.g. the wick theorem tries to create an index in the intersection between two pre-defined index spaces but then the program errors because that intersection space has not been given a name.
In particular because the error message will not contain an indication which space exactly it is missing. This essentially requires the user to dig through the SeQuant source code (to find out which spaces are pre-defined and which aren't) and then either give definitions for _all_ missing spaces or load the program into a debugger in order to figure out which index space exactly the program is missing.

Maybe at places where the program requires an intersection index, it could check whether there exists a pre-defined index space and if not, register the space on-the-fly with e.g. the combination of the parent space labels as the label.
E.g. if we intersect spaces `a` and `b`, then the intersection space could be labelled `ab`.
This wouldn't be particularly pretty, but at least the program wouldn't crash :thinking:

**Comment by evaleev** [comment]
@Krzmbrzl yes, good point re needing to have complete set of intersections ... improved error messaging by `WickTheorem` is probably the first step then ... auto registering feel more ambitious/dangerous/requires more thought.

Thanks!

**Comment by Krzmbrzl** [comment]
With the introduction of runtime index space definitions, this is likely superfluous (also potentially outdated either way)
